In [4]:
!pip install pandas

Requirement already satisfied: pandas in c:\python_hitesh choudhary\.venv\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\python_hitesh choudhary\.venv\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python_hitesh choudhary\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\python_hitesh choudhary\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\python_hitesh choudhary\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

In [6]:
pd.__version__

'3.0.0'

Creating DataFrames

In [ ]:
df = pd.DataFrame([11,22,33,44], columns=['col_name'])
df
print(type(df)) # printing type of dataframe

<class 'pandas.DataFrame'>

In [15]:
data = {
    'name':['a','b','c','d','e'],
    'Age':[16,17,18,19,20],
    'Salary':[100000,200000,300000,400000,500000]
}

In [16]:
df = pd.DataFrame(data)
df

  name  Age  Salary
0    a   16  100000
1    b   17  200000
2    c   18  300000
3    d   19  400000
4    e   20  500000

In [17]:
type(df)

pandas.DataFrame

Basic Understanding thing

In [20]:
df.head(2)

  name  Age  Salary
0    a   16  100000
1    b   17  200000

In [22]:
df.tail(2)

  name  Age  Salary
3    d   19  400000
4    e   20  500000

In [24]:
df.shape

(5, 3)

In [27]:
df.size

15

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   Age     5 non-null      int64
 2   Salary  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [30]:
df.describe()

             Age         Salary
count   5.000000       5.000000
mean   18.000000  300000.000000
std     1.581139  158113.883008
min    16.000000  100000.000000
25%    17.000000  200000.000000
50%    18.000000  300000.000000
75%    19.000000  400000.000000
max    20.000000  500000.000000

In [32]:
df.columns

Index(['name', 'Age', 'Salary'], dtype='str')

In [33]:
df.dtypes

name        str
Age       int64
Salary    int64
dtype: object

In [34]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [39]:
df.rename(columns={'salary':'Monthely_salary'},inplace=True)

In [ ]:
df.to_csv('pandas_practice_file.csv',index=False) #export dataframe

In [ ]:
load_df = pd.read_csv('pandas_practice_file.csv') # import dataframe

Row column Selction

In [ ]:
df[['name','Salary']]

  name  Salary
0    a  100000
1    b  200000
2    c  300000
3    d  400000
4    e  500000

In [60]:
df.loc[df.name == 'a']  # label based indexing
df.loc[(df.name == 'a') & (df.Salary>=40000)]

  name  Age  Salary
0    a   16  100000

In [ ]:
df.iloc[0] # index-value based 
df.iloc[0:2]

  name  Age  Salary
0    a   16  100000
1    b   17  200000